
let linguagem = 'javaScript'
let templateString = `eu estudo ${linguagem} todo dia`
console.log (templateString) 

let inteiro = 42
let decimal = 900.99
let negativo = -100
console.log (typeof inteiro,decimal,negativo)
console.log(`minha idade é ${inteiro}`)
let estaChovendo = false
console.log(estaChovendo)
let estudandoHoje = true
console.log(estudandoHoje)
let usuarioLogado = null
console.log(usuarioLogado)
console.log(typeof usuarioLogado)
